{{- if and .Values.rbac.create (not .Values.rbac.useViewRole) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-dump.fullname" . }}
  labels:
    {{- include "kube-dump.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list"]
  - nonResourceURLs: ["*"]
    verbs: ["get"]
{{- end }}

