{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-dump.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-dump.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.git.enabled .Values.git.remoteUrl }}
  git-remote-url: {{ .Values.git.remoteUrl | quote }}
  {{- end }}
  {{- if and .Values.slack.enabled .Values.slack.webhookUrl }}
  slack-url: {{ .Values.slack.webhookUrl | quote }}
  {{- end }}
{{- end }}

