apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-dump
  labels:
    app.kubernetes.io/name: kube-dump
    app.kubernetes.io/component: backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-dump
subjects:
  - kind: ServiceAccount
    name: kube-dump
    namespace: kube-system

