apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-dump

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: kube-dump
      app.kubernetes.io/managed-by: kustomize

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - secret.yaml
  - pvc.yaml
  - cronjob.yaml

